// Code generated by genx:doc DO NOT EDIT.
package devx

import (
	"github.com/xoctopus/x/docx"
)

func (v *Config) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.CI, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.Makefile, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.Lint, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *All) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "File":
			return []string{"devgen config file"}, true
		}
		return []string{}, false
	}
	return []string{"generates all configurations"}, true
}

func (v *CI) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CI":
			return []string{"if enable ci configuration generating"}, true
		}
		return []string{}, false
	}
	return []string{"generates ci configuration"}, true
}

func (v *Init) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"initializes devgen configuration"}, true
}

func (v *Lint) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Lint":
			return []string{"if enable lint generating .golangci.yml"}, true
		}
		return []string{}, false
	}
	return []string{"generates lint configuration"}, true
}

func (v *Makefile) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "TestIgnore":
			return []string{"patterns unit testing and coverage ignores", ".pb.go _mock.go _genx_ testing.go example/ will be ignored default"}, true
		case "FormatIgnore":
			return []string{"patterns code formating ignores", ".git/ .xgo/ *.pb.go *_genx_* will be ignored default"}, true
		case "Env":
			return []string{"global env variables"}, true
		case "HackTest":
			return []string{"hack test entry"}, true
		case "Depends":
			return []string{"dependent tools info"}, true
		}
		return []string{}, false
	}
	return []string{"generates go project Makefile"}, true
}

func (v *Show) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"shows devgen configuration"}, true
}

func (v *ToolType) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"make depends tool type"}, true
}

func (v *Tool) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Repo":
			return []string{}, true
		case "Version":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "Description":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Depends) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
