// Code generated by genx:doc@v0.3.8 DO NOT EDIT.
package devx

import (
	"github.com/xoctopus/x/docx"
)

func (v *Config) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.CI, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.Makefile, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.Lint, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *All) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "File":
			return []string{"devgen config file"}, true
		}
		return []string{}, false
	}
	return []string{"generates all configurations"}, true
}

func (v *CI) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CI":
			return []string{"if enable ci configuration generating"}, true
		}
		return []string{}, false
	}
	return []string{"generates ci configuration"}, true
}

func (v *Init) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"initializes devgen configuration"}, true
}

func (v *Lint) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Lint":
			return []string{"if enable lint generating .golangci.yml"}, true
		}
		return []string{}, false
	}
	return []string{"generates lint configuration"}, true
}

func (v *Target) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"target binary name, entry is cmd/<name>"}, true
		case "Image":
			return []string{"optional docker image options"}, true
		}
		return []string{}, false
	}
	return []string{"cmd/<name> build target"}, true
}

func (v *ImageOption) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Runtime":
			return []string{"base image, default alpine:latest"}, true
		case "TimeZone":
			return []string{"container timezone"}, true
		case "CgoEnabled":
			return []string{"enable CGO for image build"}, true
		case "GoProxy":
			return []string{"GOPROXY for image build"}, true
		case "Expose":
			return []string{"container expose port"}, true
		}
		return []string{}, false
	}
	return []string{"docker image build options"}, true
}

func (v *EnvVar) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Key":
			return []string{}, true
		case "Value":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *EnvVars) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *EnvShow) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Key":
			return []string{}, true
		case "Padding":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *ProjectTarget) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Entry":
			return []string{}, true
		case "Image":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *ProjectMakeData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "TestIgnores":
			return []string{}, true
		case "FormatIgnores":
			return []string{}, true
		case "Envs":
			return []string{}, true
		case "EnvShows":
			return []string{}, true
		case "GoTools":
			return []string{}, true
		case "DepFlags":
			return []string{}, true
		case "Depends":
			return []string{}, true
		case "TestDep":
			return []string{}, true
		case "BenchFlag":
			return []string{}, true
		case "HackTest":
			return []string{}, true
		case "Targets":
			return []string{}, true
		case "TargetNames":
			return []string{}, true
		case "ImageNames":
			return []string{}, true
		case "HasTargets":
			return []string{}, true
		case "HasImages":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Makefile) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "TestIgnore":
			return []string{"patterns unit testing and coverage ignores"}, true
		case "FormatIgnore":
			return []string{"patterns code formating ignores"}, true
		case "Env":
			return []string{"global env variables"}, true
		case "HackTest":
			return []string{"hack test entry"}, true
		case "Depends":
			return []string{"dependent tools info"}, true
		case "Target":
			return []string{"assigns build targets under cmd/<name>; optional image generates Dockerfile"}, true
		case "EnableBenchCover":
			return []string{"if enable bench in cover"}, true
		case "envs":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"generates go project Makefile"}, true
}

func (v *Show) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"shows devgen configuration"}, true
}

func (v *ToolType) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"make depends tool type"}, true
}

func (v *Tool) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Repo":
			return []string{}, true
		case "Version":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "Description":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Depends) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
