install:
	@echo "exported env has been inherited write your target installing"
	@echo "GIT_COMMIT = "$(GIT_COMMIT)
	@echo "GIT_TAG    = "$(GIT_TAG)
	@echo "GIT_BRANCH = "$(GIT_BRANCH)
	@echo "BUILD_AT   = "$(BUILD_AT)

image:
	@echo "exported env has been inherited write your target image building"
	@echo "GOWORK    = "$(GOWORK)
	@echo "HACK_TEST = "$(HACK_TEST)
